/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SoftwareIdRouteImport } from './routes/software.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSoftwaresRouteImport } from './routes/admin.softwares'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SoftwareIdRoute = SoftwareIdRouteImport.update({
  id: '/software/$id',
  path: '/software/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoftwaresRoute = AdminSoftwaresRouteImport.update({
  id: '/softwares',
  path: '/softwares',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/software/$id': typeof SoftwareIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/software/$id': typeof SoftwareIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/softwares': typeof AdminSoftwaresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/users': typeof AdminUsersRoute
  '/software/$id': typeof SoftwareIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/softwares'
    | '/admin/support'
    | '/admin/upload'
    | '/admin/users'
    | '/software/$id'
    | '/admin/'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/softwares'
    | '/admin/support'
    | '/admin/upload'
    | '/admin/users'
    | '/software/$id'
    | '/admin'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/softwares'
    | '/admin/support'
    | '/admin/upload'
    | '/admin/users'
    | '/software/$id'
    | '/admin/'
    | '/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  SoftwareIdRoute: typeof SoftwareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/software/$id': {
      id: '/software/$id'
      path: '/software/$id'
      fullPath: '/software/$id'
      preLoaderRoute: typeof SoftwareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/softwares': {
      id: '/admin/softwares'
      path: '/softwares'
      fullPath: '/admin/softwares'
      preLoaderRoute: typeof AdminSoftwaresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSoftwaresRoute: typeof AdminSoftwaresRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminSoftwaresRoute: AdminSoftwaresRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  SoftwareIdRoute: SoftwareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
